config-version: 2

name: 'stripe_source'
version: '0.7.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  stripe_source:
    materialized: table
    +schema: stg_stripe
    tmp:
      materialized: view

vars:
  stripe_source:
    balance_transaction: "{{ source('stripe', 'balance_transaction') }}"
    card: "{{ source('stripe', 'card') }}"
    charge: "{{ source('stripe', 'charge') }}"
    customer: "{{ source('stripe', 'customer') }}"
    dispute: "{{ source('stripe', 'dispute') }}"
    fee: "{{ source('stripe', 'fee') }}"
    invoice: "{{ source('stripe', 'invoice') }}"
    invoice_line_item: "{{ source('stripe', 'invoice_line_item') }}"
    payment_intent: "{{ source('stripe', 'payment_intent') }}"
    payment_method_card: "{{ source('stripe', 'payment_method_card') }}"
    payment_method: "{{ source('stripe', 'payment_method') }}"
    payout: "{{ source('stripe', 'payout') }}"
    plan: "{{ source('stripe', 'plan') }}"
    refund: "{{ source('stripe', 'refund') }}"
    subscription_history: "{{ source('stripe', 'subscription_history') }}"
    subscription: "{{ source('stripe', 'subscription') }}"
    credit_note: "{{ source('stripe', 'credit_note') }}"
    credit_note_line_item: "{{ source('stripe', 'credit_note_line_item') }}"

    #Variables to enable or disable models if you do not have the respective table.
    using_invoices: true
    using_credit_notes: false
    using_payment_method: true
    using_subscriptions: true

    # variable to exclude or include historical subscription data
    stripe__subscription_history: false

    # variable to exclude or include test data (based on `livemode`)
    using_livemode: true

    # variable to disable the filter within invoice line item
    using_invoice_line_sub_filter: true
